### ISSUE TITLE
Draft Dweb Camp Pillars

### ISSUE THREAD

**Issue by whanamura** [dweb-camp-2019/communication#7]
We gathered a group of 5 organizers to hash out a set of "first principles" for the camp.
Here's what we came up with.  Please leave your comments!
https://docs.google.com/document/d/1wjr-nSdpi4f1E4Vg31N6HTDOR5r4qCD4pig-CirSllg/edit?usp=sharing

**Comment by kriskeillor** [comment]
Looks really good! Appreciate the brevity!

**Comment by whanamura** [comment]
Published here: https://dwebcamp.org/about/
